# **Inteligencia Artificial y Aprendizaje Automático**
## **Maestría en Inteligencia Artificial Aplicada**
### **Dr Luis Eduardo Falcón Morales**
### **Tecnológico de Monterrey**
## **Actividad Individual Semana 9: Pronósticos con Series de Tiempo**

#### **Nombre: Alexandro Mayoral Terán**
#### **Matrícula: A01795899**

In [1]:
# Librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import mean_squared_error
import math

from prophet import Prophet
from statsmodels.graphics.tsaplots import month_plot, quarter_plot
from statsmodels.tsa.seasonal import seasonal_decompose
from statsmodels.graphics.tsaplots import plot_acf, plot_pacf   # gráficos de autocorrelación

import tensorflow as tf
import keras
from keras import Sequential
from keras import layers
from keras.layers import LSTM, Dense

### Preparación de los datos

In [3]:
file_name = 'monthly_champagne_sales.csv'
data = pd.read_csv(file_name)
data.head()

     Month  Sales
0  1964-01   2815
1  1964-02   2672
2  1964-03   2755
3  1964-04   2721
4  1964-05   2946

In [4]:
data.info() # Observamos que la fecha es una variable de tipo objeto o categórica.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 105 entries, 0 to 104
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Month   105 non-null    object
 1   Sales   105 non-null    int64
dtypes: int64(1), object(1)
memory usage: 1.8+ KB

In [5]:
# Renombramos de manera estándar las columnas de fechas y valores de
# la serie de tiempo, donde además la fehhca la transformamos a tipo datetime:
data.columns = ['ds', 'y']
data['ds'] = pd.to_datetime(data['ds'])
data.head()

          ds     y
0 1964-01-01  2815
1 1964-02-01  2672
2 1964-03-01  2755
3 1964-04-01  2721
4 1964-05-01  2946

In [6]:
# Hacemos una copia del data frame 'data' con indices temporales:
data_temp = data.copy()
data_temp.set_index('ds', inplace=True)
data_temp.head()

               y
ds
1964-01-01  2815
1964-02-01  2672
1964-03-01  2755
1964-04-01  2721
1964-05-01  2946

In [7]:
print(data.shape)
print(data_temp.shape)

(105, 2)
(105, 1)

In [13]:
# Ajustamos la frecuencia de los índices, para que el modelo tenga información del período en que
# se encuentran los datos:
# Especifiquamos entonces que nuestros datos están registrados con una frecuencia mensual:
data_temp.index.freq = 'MS'  # MS-Month-start-frequency o M=ME-Month-end-frequency
data_temp.index

DatetimeIndex(['1964-01-01', '1964-02-01', '1964-03-01', '1964-04-01',
               '1964-05-01', '1964-06-01', '1964-07-01', '1964-08-01',
               '1964-09-01', '1964-10-01',
               ...
               '1971-12-01', '1972-01-01', '1972-02-01', '1972-03-01',
               '1972-04-01', '1972-05-01', '1972-06-01', '1972-07-01',
               '1972-08-01', '1972-09-01'],
              dtype='datetime64[ns]', name='ds', length=105, freq='MS')

In [ ]:
# Particionamos en entrenamiento y prueba como DataFrames de Pandas:
train = data_temp.iloc[0:-12,:]
test = data_temp.iloc[-12:,:]   # Seleccionamos los datos del último año para predicción de Test.

### Modelo ingenuo

### Modelo ARIMA

### Modelo Prophet

### Modelo LSTM

## **<<< Fin de la Actividad de la Semana - Pronósticos y Series de Tiempo >>>**